# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  blazorserver:
    image: blazorserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7080:80
      - 7443:443